### ISSUE TITLE
автор специально кидал ошибки в коде ? 

### ISSUE THREAD

**Issue by Hellomik2002** [alexgolikov/deep-learning-book#1]

**Comment by alexgolikov** [comment]
Как указано, всё работает на версиях Python 3.6.4, Tensorflow 1.6.0, Keras 2.1.5. Если у Вас другие версии, то есть вероятность, что что-то может не работать. 
Напишите, где именно и какая ошибка, возможно, Вам кто-то поможет. Если Вы сами знаете, как исправить, то пуллриквест приветствуется.

**Comment by Hellomik2002** [comment]
я имел виду саму книгу, но если вы свободны то можно  я здесь буду вас задавать вопросы ?

**Comment by alexgolikov** [comment]
Задавайте, кто-нибудь да ответит.
